language: python
python:
- '3.5'
env:
  global:
    - GH_REPO="github.com/firsttris/repository.sendtokodi.git"
    - GH_REPO_PYTHON3="github.com/firsttris/repository.sendtokodi.python3.git"
    - YOUTUBE_DL="https://github.com/rg3/youtube-dl/archive/master.zip"
    - VERSION=0.0.${TRAVIS_JOB_NUMBER}
    - ADDON_NAME="plugin.video.sendtokodi"
    - REPO_NAME="repository.sendtokodi"
    - REPO_NAME_PYTHON3="repository.sendtokodi.python3"
    - NAME="sendtokodi"
script:
- rm -rf .git/
# LATER - envsubst < "addon.template.xml" > "addon.xml"
- cd ..
# youtube_dl
- wget ${YOUTUBE_DL}
- unzip master.zip
- cp -R youtube-dl-master/youtube_dl ${ADDON_NAME}
# clone repo
- git clone https://${GH_REPO}
- git clone https://${GH_REPO_PYTHON3}
# create addon
- envsubst < "${REPO_NAME}/${ADDON_NAME}/addon.template.xml" > "${REPO_NAME}/${ADDON_NAME}/addon.xml" #python 2 version
- envsubst < "${REPO_NAME_PYTHON3}/${ADDON_NAME}/addon.template.xml" > "${REPO_NAME_PYTHON3}/${ADDON_NAME}/addon.xml" #python 3 version
- zip -r ${ADDON_NAME}-${VERSION}.zip ${ADDON_NAME} # create zip
- cp ${ADDON_NAME}-${VERSION}.zip ${REPO_NAME}/${ADDON_NAME}/ # copy source code to python 2 repo
- cp ${ADDON_NAME}-${VERSION}.zip ${REPO_NAME_PYTHON3}/${ADDON_NAME}/ # copy source code to python 3 repo
# commit & push to python 2 repo
- cd ${REPO_NAME}/
- envsubst < "addon.template.xml" > "addon.xml"
- md5sum addon.xml > addon.xml.md5
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
## go back one folder
- cd ..
# commit & push to python 3 repo
- cd ${REPO_NAME_PYTHON3}/
- envsubst < "addon.template.xml" > "addon.xml"
- md5sum addon.xml > addon.xml.md5
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REPO_PYTHON3}" master > /dev/null 2>&1